"""Instructions for regenerating Firebase service account key.

This script provides step-by-step instructions for fixing the corrupted Firebase key.
"""
import os

def print_instructions():
    print("=" * 60)
    print("FIREBASE SERVICE ACCOUNT KEY REGENERATION INSTRUCTIONS")
    print("=" * 60)
    print()
    print("Your Firebase service account key is corrupted and cannot be fixed.")
    print("You need to generate a new one from the Firebase Console.")
    print()
    print("STEP 1: Go to Firebase Console")
    print("   • Open https://console.firebase.google.com/")
    print("   • Select your project: groot-f61e8")
    print()
    print("STEP 2: Navigate to Service Accounts")
    print("   • Click on the gear icon (Project Settings)")
    print("   • Go to the 'Service accounts' tab")
    print("   • Scroll down to 'Firebase Admin SDK'")
    print()
    print("STEP 3: Generate New Private Key")
    print("   • Click 'Generate new private key'")
    print("   • Confirm the action")
    print("   • Download the JSON file")
    print()
    print("STEP 4: Replace the Corrupted Key")
    print("   • Rename the downloaded file to 'firebase-key.json'")
    print("   • Replace the existing file at: config/firebase-key.json")
    print("   • Make sure the file contains all required fields:")
    print("     - type: 'service_account'")
    print("     - project_id: 'groot-f61e8'")
    print("     - private_key: '-----BEGIN PRIVATE KEY-----...'")
    print("     - client_email: 'firebase-adminsdk-...@groot-f61e8.iam.gserviceaccount.com'")
    print("     - client_id, auth_uri, token_uri, etc.")
    print()
    print("STEP 5: Test the New Key")
    print("   • Run: python test_firebase_init.py")
    print("   • You should see: 'Firebase initialized OK'")
    print()
    print("CURRENT PROJECT INFO:")
    print(f"   • Project ID: groot-f61e8")
    print(f"   • Service Account: firebase-adminsdk-fbsvc@groot-f61e8.iam.gserviceaccount.com")
    print(f"   • Key file location: {os.path.join('config', 'firebase-key.json')}")
    print()
    print("BACKUP CREATED:")
    print(f"   • Original corrupted key saved as: config/firebase-key.json.backup")
    print()
    print("=" * 60)

if __name__ == "__main__":
    print_instructions()
